channels:
  - conda-forge
dependencies:
  - r-base=4.1.3
  - r-irkernel
  - r-tidyverse
  - r-readxl
  - r-haven
  - r-remotes
  - r-devtools
  # Data Handling
  - r-naniar
  - r-fastdummies
  # R Markdown
  - r-rmarkdown
  - r-quarto
  - r-formatR
  - r-summarytools
  - r-gt
  - r-kableExtra
  # Estimation
  - r-estimatr
  - r-margins
  - r-prediction
  - r-modelsummary
  # Visualization
  - r-ragg
  - r-gt
