#!/bin/bash

wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.0.38/quarto-1.0.38-linux-amd64.deb
gdebi quarto-1.0.38-linux-amd64.deb

Rscript setup_cran.R

Rscript setup_gh.R

rm apt.txt README.md environment.yml postBuild setup_cran.R setup_gh.R quarto-1.0.38-linux-amd64.deb
